apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubernetes-cron-job
spec:
  schedule: "0,15,30,45 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
            - name: kube-cron-job
              image: devopscube/kubernetes-job-demo:latest
              args: ["100"]
