apiVersion: batch/v1
kind: Job
metadata:
  generateName: kube-job-prefix-
  labels:
    jobgroup: jobexample
spec:
  completions: 6
  parallelism: 2
  template:
    metadata:
      name: kubernetes-parallel-job
      labels:
        jobgroup: jobexample
    spec:
      containers:
        - name: c
          image: devopscube/kubernetes-job-demo:latest
          args: ["100"]
      restartPolicy: OnFailure
